name = "Nodia"
grammar = "nodia"
path_suffixes = ["nod"]
line_comments = ["# ", "// "]
tab_size = 2
hard_tabs = false
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["comment"] }
]
