#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub column: usize,
}

impl Token {
    pub fn new(kind: TokenKind, line: usize, column: usize) -> Self {
        Self { kind, line, column }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Let,
    Const,
    Fn,
    Return,
    Emit,
    If,
    Else,
    For,
    In,
    While,
    Break,
    Continue,
    True,
    False,
    Null,
    And,
    Or,
    Not,
    Import,
    From,
    As,
    Match,
    Case,
    Default,
    Try,
    Catch,
    Throw,
    Defer,
    Type,
    Enum,
    Struct,
    Namespace,
    Use,
    Identifier(String),
    Int(i64),
    Float(f64),
    String(String),
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equal,
    EqualEqual,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Colon,
    Semicolon,
    Newline,
    Eof,
}

pub fn keyword_kind(text: &str) -> Option<TokenKind> {
    Some(match text {
        "let" => TokenKind::Let,
        "const" => TokenKind::Const,
        "fn" => TokenKind::Fn,
        "return" => TokenKind::Return,
        "emit" => TokenKind::Emit,
        "if" => TokenKind::If,
        "else" => TokenKind::Else,
        "for" => TokenKind::For,
        "in" => TokenKind::In,
        "while" => TokenKind::While,
        "break" => TokenKind::Break,
        "continue" => TokenKind::Continue,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "null" => TokenKind::Null,
        "and" => TokenKind::And,
        "or" => TokenKind::Or,
        "not" => TokenKind::Not,
        "import" => TokenKind::Import,
        "from" => TokenKind::From,
        "as" => TokenKind::As,
        "match" => TokenKind::Match,
        "case" => TokenKind::Case,
        "default" => TokenKind::Default,
        "try" => TokenKind::Try,
        "catch" => TokenKind::Catch,
        "throw" => TokenKind::Throw,
        "defer" => TokenKind::Defer,
        "type" => TokenKind::Type,
        "enum" => TokenKind::Enum,
        "struct" => TokenKind::Struct,
        "namespace" => TokenKind::Namespace,
        "use" => TokenKind::Use,
        _ => return None,
    })
}
